ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
COMMAND_ENABLE = no # for space_cadet
SPACE_CADET_ENABLE = no
MOUSEKEY_ENABLE = yes # bigger size
CAPS_WORD_ENABLE = yes
WPM_ENABLE = yes

# Reduce compiled size
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
MUSIC_ENABLE = no`