ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes # bigger size
CAPS_WORD_ENABLE = yes
WPM_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

# Reduce compiled size
GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no

# Try to make keyboard usable in uefi
SLEEP_LED_ENABLE=no